on: push
  #push:
    #tags:
     #- 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_USER: realcodemeteor
  DOCKER_REPOSITORY: codemeteor
  DOCKER_IMAGE_NAME: cloudflare-dyndns-updater
  DOCKER_TAG: "date +%s"
jobs:
  build:
    
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo $DOCKER_USER/$DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:$($DOCKER_TAG)
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_REPOSITORY/$DOCKER_IMAGE_NAME:$($DOCKER_TAG)
          
