on: push
  #push:
    #tags:
     #- 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from my first GitHub action"
